apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-aplicacion-deployment
spec:
  selector:
    matchLabels:
      version: green
  template:
    metadata:
      labels:
        version: green
    spec:
      containers:
      - name: app
        envFrom:
        - configMapRef:
            name: mi-aplicacion-config-green
        env:
        - name: DEPLOYMENT_COLOR
          value: "green"
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: mi-aplicacion-config-green
              key: PROJECT_PORT
