apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - hpa.yml
nameSuffix: "-green"
patches:
  - path: deployment-patch.yml
    target:
      kind: Deployment
  - path: project-deployment-patch.yml
    target:
      kind: Deployment
patchesJson6902:
  - target:
      kind: Deployment
      name: rx-mi-aplicacion-deployment-green
    path: health-path-patch.json
images:
  - name: mi-aplicacion
    newName: mi-aplicacion
    newTag: "latest"
replicas:
  - name: rx-mi-aplicacion-deployment
    count: 1
