# Generado por scripts/generate-configmap.sh — no editar manualmente
apiVersion: v1
kind: ConfigMap
metadata:
  name: mi-aplicacion-config
data:
  APP_COLOR: "yellow"
  CONTAINER_IP: "180.28.1.1"
  DOCKER_COMPOSE_APP: "docker-compose.dev.yml"
  ENV_FILE: ".env-algo"
  HEALTH_PATH: "/health"
  HOST_DB: "db.local:172.20.0.2"
  NETWORK: "my-network"
  NETWORK_NAME: "cubiko"
  NETWORK_SUBNET: "180.28.0.0/16"
  NETWORK_SWARM: "my-network-swarm"
  PORTS: "5050:80"
  PROJECT_IMAGE: "mi-aplicacion"
  PROJECT_NAME: "mi-aplicacion"
  PROJECT_NGINX_DIR: "/app/nginx/snippet.conf"
  PROJECT_PORT: "3000"
  PROJECT_SOURCE: "app"
  PROJECT_VERSION: "latest"
  REPLICAS: "3"
