apiVersion: v1
kind: Service
metadata:
  name: rx-mi-aplicacion-service
spec:
  type: NodePort
  selector:
    app: rx-mi-aplicacion
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      nodePort: 30080
